### ISSUE TITLE
[BUG] Can't update Steam avatars

### ISSUE THREAD

**Issue by Hannumn** [sw2719/steam-account-switcher#56]
Updating avatars for Steam accounts errors, program freezes on the "Please wait while downloading avatars..." screen and an error code displayed in console.

`Traceback (most recent call last):
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\Users\DESKTOP\Desktop\Games\steam-account-switcher-master\modules\main.py", line 862, in update_avatar
    download_avatar(dl_list)
  File "C:\Users\DESKTOP\Desktop\Games\steam-account-switcher-master\modules\avatar.py", line 57, in download_avatar
    loop.run_until_complete(main())
  File "C:\Users\DESKTOP\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Users\DESKTOP\Desktop\Games\steam-account-switcher-master\modules\avatar.py", line 52, in main
    async with aiohttp.ClientSession as session:
AttributeError: __aexit__`

To Reproduce
1. Menu
2. Update all avatars

Environment
 - OS: Windows 10 x64 v20H2 (OS Build 19042. 1889)
 - Steam Account Switcher: v2.8

**Comment by andrey545454** [comment]
The Source code information section says that "At least Python 3.7 is required", but you are using a version below the specified one.

**Comment by Hannumn** [comment]
This should be my moment to upgrade python, thanks.

![charles-leclerc-i-am-stupid](https://user-images.githubusercontent.com/66778560/192880072-9a62901e-d0cc-4654-ab71-f5e3678b63f7.gif)
